language: java

jdk: openjdk8

script:
 - echo "Hola travis"
 - mvn package
 - ssh-keyscan -H 3.134.49.225 >> ~/.ssh/known_hosts
 - ssh-keyscan -H ec2-3-134-49-225.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
 - scp -i acceso_instancia.pem target/*.war ubuntu@3.134.49.225:/tmp